// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-319IuFFAAotDNzKMYpxXND5XhE7s1Y',
    appId: '1:36434087690:web:e0890f2fac5126f9d874f3',
    messagingSenderId: '36434087690',
    projectId: 'automatic-palm-tree',
    authDomain: 'automatic-palm-tree.firebaseapp.com',
    storageBucket: 'automatic-palm-tree.firebasestorage.app',
    measurementId: 'G-KKZNVW660W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7CLvmQe0ktsHZfL6oSiRfcvoVyJNqbs',
    appId: '1:36434087690:android:fe84cd6365a335ddd874f3',
    messagingSenderId: '36434087690',
    projectId: 'automatic-palm-tree',
    storageBucket: 'automatic-palm-tree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehqBvW9bw16XYAjxwZnS_qSC6dWeaEnA',
    appId: '1:36434087690:ios:4c26dffcdcc2f8c4d874f3',
    messagingSenderId: '36434087690',
    projectId: 'automatic-palm-tree',
    storageBucket: 'automatic-palm-tree.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehqBvW9bw16XYAjxwZnS_qSC6dWeaEnA',
    appId: '1:36434087690:ios:4c26dffcdcc2f8c4d874f3',
    messagingSenderId: '36434087690',
    projectId: 'automatic-palm-tree',
    storageBucket: 'automatic-palm-tree.firebasestorage.app',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-319IuFFAAotDNzKMYpxXND5XhE7s1Y',
    appId: '1:36434087690:web:416b68a4e9feb51dd874f3',
    messagingSenderId: '36434087690',
    projectId: 'automatic-palm-tree',
    authDomain: 'automatic-palm-tree.firebaseapp.com',
    storageBucket: 'automatic-palm-tree.firebasestorage.app',
    measurementId: 'G-TVP7V98CEQ',
  );

}